<link rel="stylesheet" type="text/css" href="styles/navbarStyles.css">
<link rel="stylesheet" type="text/css" href="styles/flexboxClasses.css">
<link rel="stylesheet" type="text/css" href="styles/sidebarStyles.css">
<link rel="stylesheet" type="text/css" href="styles/shapesImagesStyles.css">
<link rel="stylesheet" type="text/css" href="styles/effectsStyles.css">
<link rel="stylesheet" type="text/css" href="styles/marginPaddingStyles.css">
<link rel="stylesheet" type="text/css" href="styles/widthHeightStyles.css">
<link rel="stylesheet" type="text/css" href="styles/generalStyles.css">
<link rel="stylesheet" type="text/css" href="styles/textStyles.css">